### ISSUE TITLE
Remove default list padding from nav lists?

### ISSUE THREAD

**Issue by davidhund** [csstools/sanitize.css#10]
I guess the `$default-nav-list-style` is `none` because you assume navigation lists should not be styled as lists. Do we not have to remove the default (left-)padding too then?

```
nav ol,
nav ul {
    list-style: $default-nav-list-style;
    padding-left: 0;
}
```

**Comment by jonathantneal** [comment]
Is this [already covered](https://github.com/jonathantneal/sanitize.css/blob/master/sanitize.scss#L123)?

**Comment by davidhund** [comment]
Doh! Obviously. 
I guess I'm not really used to that 'nuclear reset' anymore ;)

(It might be a bit too nuclear for my taste b.t.w. see also https://twitter.com/kilianvalkhof/status/578610583114756097)

**Comment by jonathantneal** [comment]
That is a tangent from this issue, but you are welcome to open a new issue for this if you like. I don’t agree that the user agent pre-aligned vertical rhythm is necessary or desired out of the box. The default spacing rhythm is a kind of theme, and many css libraries ditch the defaults in order to assign their own spacing rhythms. For example, both [Bootstrap](https://github.com/twbs/bootstrap/blob/master/less/type.less) and [Foundation](https://github.com/zurb/foundation/blob/master/scss/foundation/components/_type.scss) do this.
