### ISSUE TITLE
Use :root instead of html

### ISSUE THREAD

**Issue by thasmo** [csstools/sanitize.css#104]
I've noticed `html` is used instead of `:root` in the new v4 release. Was this done on purpose? `svg:not(:root)` is still used somewhere, not using `html`.

Would it make sense to use `:root` everywhere?

**Comment by jonathantneal** [comment]
The short answer is: `html` could be changed back to `:root` in a minor release. It was originally done to avoid confusion between `html` and `body` as far as it relates to where you put a background.

The long answer:

> The background of the root element becomes the background of the canvas and covers the entire canvas.

Ah, so we put backgrounds on `:root`.

> For HTML documents, however, we recommend that authors specify the background for the BODY element rather than the HTML element.

Ah, so we put backgrounds on `body`.

Except it’s a bit frustrating when [these rules](https://www.w3.org/TR/CSS2/colors.html#background) pre-date `:root`, and since this time many developers have split preference between styling the canvas from the safer `html` or `:root` or the traditional and spec-recommended `body`.

In the end, I pulled background and foreground styling from sanitize.css; party because of this issue, but namely because it wasn’t necessary to style. You want to prepare for this situation when a visitor has an alternative color scheme, which is most likely [high contrast mode](http://webaim.org/blog/high-contrast/). You should design your site for that scenario separately.

Beyond consistency, are there any other reasons you wanted it switched back?

**Comment by thasmo** [comment]
Nope, no other reasons. Thanks for explaining it!

**Comment by indrekpaas** [comment]
I've noticed specificity being kept as low as possible in this library. Just an FYI `:root` has higher specificity than `html`: 0010 and 0001 respectively.

**Comment by jonathantneal** [comment]
Well, it’s a nice bonus to lower the selector weight.
