### ISSUE TITLE
To be used alongside normalize?

### ISSUE THREAD

**Issue by rowild** [csstools/sanitize.css#113]
Hi, 

the readme is quite a bit confusing for me: is sanitize to be used together with normalize or not?
Would be great, if the readme could immediately clarify that.

Thank you!

**Comment by rowild** [comment]
Any hints?

**Comment by ghost** [comment]
I think you should use them separated, both solve the same problem but in a different way. Normalize just makes every browser render elements consistently between them and Sanitize too but by providing more useful defaults.

**Comment by jonathantneal** [comment]
@rowild, as @jameskolce has said, both projects resolve the inconsistencies between browsers, which is why they share so much code.

normalize.css generally follows a combination of the [CSS Specifications](https://wiki.csswg.org/spec) and an implementation consensus among browser vendors.

sanitize.css generally follows what [developers and the CSS Working Group themselves wish the spec might have been](https://wiki.csswg.org/ideas/mistakes). Remember, we cannot change the spec, because of backwards compatibility. This is why sanitize.css exists.

**Comment by dixhuit** [comment]
IMHO It's still not clear enough from the README alone (hence me still feeling like I need to search the issues for "normalize" and arriving here).

What would be helpful is if the following points could be clearly spelled out (assuming I've understood the facts but there lies the issue I guess):

1. **The what**: Use one or the other, no need for both.
2. **The why**: Using sanitize.css provides the benefits of normalize.css as well as several (sometimes opinionated) additions on top (_"maintained in sync"_ can be interpreted in too many different ways and doesn't communicate this clearly enough).
