### ISSUE TITLE
label and summary cursor

### ISSUE THREAD

**Issue by bes-internal** [csstools/sanitize.css#132]
Suggest
```
label, summary {cursor:pointer}
```
playground at https://codepen.io/anon/pen/YVPQqK

**Comment by jonathantneal** [comment]
I like this because part of me expects anything mouse-interactive on the web to get `cursor:pointer`. However, outside the browser, I don’t expect this. Hover over buttons outside a browser, for instance.

I see OS-like behavior on these elements. For instance, the cursor does not change into text when you hover over them, but instead remains a cursor.

We should see if this has been discussed by other projects or usability experts and then decide whether to switch this or not. Thanks for sharing it!

**Comment by jonathantneal** [comment]
I may end up adding this.

**Comment by wulfsberg** [comment]
I don't think it makes sense that the label has a pointer, but the associated checkbox does not. That seems to specifically _disconnect_ the two, hinting that one is an input and the other is a link.

**Comment by jonathantneal** [comment]
I agree with @wulfsberg, as well as https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b and so I will not be adding this.
