### ISSUE TITLE
Alignment with Normalize releases

### ISSUE THREAD

**Issue by gunnx** [csstools/sanitize.css#135]
Hi,
What is the plan to align with normalize releases, version 7.0.0 of normalize was released in March this year, do you release a version 7.0.0 of sanitize to match?
Thanks

**Comment by jonathantneal** [comment]
There will no longer be alignment with necolas/normalize.css. The Normalize.css v7 release contained absolutely no fixes. See for yourself:

https://github.com/necolas/normalize.css/commit/b4a8fdaf8321093b1e3cad612fb76cf2b7d3275d

You’ll see it only restored opinionated changes, most of which were already in sanitize.css:

https://github.com/jonathantneal/sanitize.css/blob/master/sanitize.css#L58-L64
https://github.com/jonathantneal/sanitize.css/blob/master/sanitize.css#L333-L341

I created normalize.css with Nicolas on IRC. You can see me making all sorts of mistakes in the first 12 commits to the project, some of which I removed in v6 and were put back in v7:

https://github.com/necolas/normalize.css/commits/master/normalize.css?after=341f0af212f4ba4592ea3d2699719b9a688c0fd2+0

He did not like where I was taking the project, so he kicked me off that project a few weeks ago, claimed I had stolen code from him, and locked everyone out the conversation.

https://github.com/necolas/normalize.css/issues/664#issuecomment-298708485

As part of non-functional maintenance, he wiped our names from the credits.

https://github.com/necolas/normalize.css/commit/62b4a86c2863f5a4475d8fb98ddf1b927d7d7bfb

I am still addicted to keeping normalize.css up to date, which is why I released my own normalize.css 7.0.0 (https://github.com/jonathantneal/normalize.css) that continues down the path of maintenance:

- [Updates the browser landscape for abbr[title] fixes](https://github.com/jonathantneal/normalize.css/commit/e3d23fd306b1534959199fdf801d70eaee2b5305)
- [Corrects the browser landscape for displays](https://github.com/jonathantneal/normalize.css/commit/4c55d4d29ef0c3345a859ea0542c05364fd601f8)
- [Updates the browser landscape for details](https://github.com/jonathantneal/normalize.css/commit/2c6376d3b86d25f651cd5428ca88943a1c7402d3)

As well as a further withdrawal from opinionated rules:

- [Removes the sub and sup opinionated resets](https://github.com/jonathantneal/normalize.css/commit/1880b36408d010c05efd561f7c096907cc0b4d0d)

However, Nicolas has the keys to everything named normalize.css, and my name is wiped as a co-creator, so I will probably seek out a new name for *the project I created with Nicolas formally known as normalize.css*, and then possibly rename this project as well. He recommended as much:

> If people want to develop and use alternative approaches, those can be worked on as separate projects (as normalize.css was to reset.css).

I hope this doesn’t disappoint you, but helps you understand why I can’t safely rely on normalize.css anymore.
