### ISSUE TITLE
Responsive img

### ISSUE THREAD

**Issue by boulaffasae** [csstools/sanitize.css#170]
Please consider adding proprety `max-width` to img, if img used in article it go out of the wrapper `article`

```
img {
  max-width: 100%;
}
```

**Comment by jonathantneal** [comment]
Until we have a reliable property in all supported browsers like `aspect-ratio`, adding `max-width` doesn’t fix the problem of oversized images, it just changes it into a problem of stretched images.

That being said, if you have some blogs or documentation that explains why you think the trade off is better this way, I‘d consider adding it.

**Comment by TomS-** [comment]
@jonathantneal in all my years of CSS I don't think I've ever come across max-width: 100% stretching images. As this is the go to solution for making images responsive, do you have an example of where and in which browser max-width: 100% is stretching images? I'd like to learn the argument against it.

**Comment by jonathantneal** [comment]
> in all my years

I learn new things all the time. For simplicity sake, this example inlines the relevant CSS:

```html
<div style="width:200px">
  <img src="https://placeimg.com/640/480/people/1" width="640" height="480" style="max-width:100%">
</div>
```

It is badly stretched. Now, compare that with the `height:auto` version:

```html
<div style="width:200px">
  <img src="https://placeimg.com/640/480/people/1" width="640" height="480" style="max-width:100%;height:auto">
</div>
```

The `width` and `height` attributes on an `<img>` preserve the space it needs before it loads, removing the shift of content one otherwise experiences. However, adding `max-width` fouls up the aspect ratio, which often leads to:

```css
img {
  height: auto;
  max-width: 100%;
}
```

Doing this undoes the `width` and `height` abilities of `<img>`. Maybe you don’t code this way. Plenty others do, as it’s really useful, and a driving factor in the `aspect-ratio` property being pitched. I’d prefer not to break this feature.

An alternative is to make the selector more abrasive:

```css
img:not([width]) {
  max-width: 100%;
}
```

However, this project tries its best to avoid multi-weight selectors.
