### ISSUE TITLE
Question: Why was the border box rule changed?

### ISSUE THREAD

**Issue by mattpilott** [csstools/sanitize.css#193]
Hey,

I see way back in v6 the border-box rule was changed from inherit from html to being explicitly defined, why was this decision made out of interest?

Thanks

**Comment by hacknug** [comment]
I believe it was because pseudo elements don't inherit the value from their parent: https://github.com/csstools/sanitize.css/blob/master/CHANGELOG.md#600-june-24-2018

EDIT: Here's a comment from @jonathantneal explaining why https://github.com/mozdevs/cssremedy/issues/4#issuecomment-465698966

**Comment by jonathantneal** [comment]
@matt3224, that’s a fair question. I dropped the inheritance strategy for 2 reasons.

1. The CSSWG has determined that [box-sizing should be `border-box` by default](https://wiki.csswg.org/ideas/mistakes). However, to keep the web backwards compatible, specs and browsers will continue shipping `content-box` as the default. Therefore, making `border-box` the default in sanitize.css is more “standards facing” than the inheritance strategy.
2. The individual “responsible” for the inheritance strategy now agrees with the CSSWG. I know because [I am that person](https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/).

My motivation for the inheritance strategy was to “_make it easier to change the box-sizing in plugins or other components that leverage other behavior._” That was only a good interim strategy while browsers like Internet Explorer 5-6 did not support `border-box`, and browsers like Firefox 3-22 required a `moz` prefix.
