### ISSUE TITLE
other performance oriented global styles

### ISSUE THREAD

**Issue by paulirish** [csstools/sanitize.css#2]
``` css
* { 
  position:relative;
  overflow:hidden; 
}
```

https://twitter.com/paul_irish/status/524959136782364672

**Comment by jonathantneal** [comment]
`box-sizing: border-box`
Totally awesome! It’s my favorite part of this stylesheet for sure.

`display: flex`
Seems troublesome! I’m unconvinced setting a singular display on all elements is useful in an application or a standard page, which is probably why you saw [the definition overwritten for inline elements later](https://twitter.com/paul_irish/status/524980393775091713/photo/1).

`flex-flow: column`
Sweet! This is only overwriting the default `flex-direction` that us normally set to `row`, correct? Is it doing anything else? Very interesting and definitely worth testing.

`flex-shrink: 0`
Whoa, neat! This used to be the default, but [it was changed](https://github.com/philipwalton/flexbugs#6-the-default-flex-value-has-changed). Definitely worth learning why it was changed and then making a call.

`overflow: hidden`
Seems troublesome! This may have really undesirable effects on [font ascenders and descenders](http://facweb.cs.depaul.edu/sgrais/images/4Sculptures/Type2.4.gif) as well as on text and box shadows.

`position: relative`
Whoa, neat! I’ll need to find or make some test cases and see how many of today’s designs would benefit from specifying static as the exception. This would be awesome because it would normalize and simplify `top`, `right`, `bottom`, and `left` expectations. I would be most concerned about designs with a lot of [divitus](https://css-tricks.com/css-beginner-mistakes-1/).

**Comment by paulirish** [comment]
Aye.

TBH I'm only advocating for the last two here.

`overflow:hidden` has significant performance benefits because elements can become layout boundaries and contain layout costs easier.  descenders should very rarely be cut, as elements by default will allow the line box to fit. 

`pos:rel` is really worth playing with. it's easier for blink (at least, and i presume others) to lay out elements as relative instead of static. 

you can see that the combination of these two turns everything into components built out of other components. turns out that's something the browser can reason about very well.

**Comment by jonathantneal** [comment]
So far, `position: relative` is a big hit with me and some other developers brave enough to try it in websites they are building. Particularly, I was curious how it might break WordPress’ admin bar. The answer? Not at all, that I can see so far. I’m almost positive this is making it in.

I can’t explain it, but `overflow: hidden` is starting to grow on me. Every person I talked with about this rejected it, as did I. And yes, after I threw it in my local copy of sanitize, I immediately found places where I needed to specify overflow: visible to fix display issues. However, after two or three specific `visible` definitions, all was better. I was so surprised. Then it dawned on me that margins could now be used more sensibly, rather than breaking out of the expected box. So, I’ve kept this in my own version, but I’ll still need to see how others experience it.

Also, how might these performance improvements be tested and proved? Not that I don’t trust Chrome developers, but if the gains are significant, that would probably blow people’s minds.

**Comment by crswll** [comment]
I ran into a situation that caught me off guard using `overflow: hidden`. When you want to wrap something around a floating element it doesn't allow it as you'd expect. Easy enough to adjust for but still might trip people up. Here's a demo: http://jsbin.com/colewa/1/edit?html,css,output

**Comment by paulirish** [comment]
good call. wrapped text around a floated item will have to be whitelisted
to visible.​

**Comment by paulirish** [comment]
> Also, how might these performance improvements be tested and proved? Not that I don’t trust Chrome developers, but if the gains are significant, that would probably blow people’s minds.

easiest way would be to take a pretty complex layout job (like nytimes.com or cnn.com) and measure both page load and some interaction like moving carousel or openting settings.  record all of that in devtools timeline.   (you could use Webpagetest which can collect it). then you're interested in Layout cost ONLY. we should see a difference between the two. 

webapp scenarios will have this difference be more exaggerated.

**Comment by tozz** [comment]
I've been playing around with `overflow: hidden` and the only problem I've noticed is that `inline-block` elements starts to become unwieldy, can't explain why though (it's not white space related, I've tried both with and without minified HTML).

**Comment by tozz** [comment]
I found another really annoying thing with `overflow: hidden`, it breaks Google Maps. You can't rely on inherit either as the parent divs set `overflow: hidden` in the API, the children however needs to be visible.

**Comment by robwierzbowski** [comment]
I actually have issues with universal `overflow:hidden` and `pos:relative` on many of my projects. Floating, getting fancy with responsive layouts, hanging list items and other fancy typography. I think this might be one step too specific for a generic, widely used baseline package.

**Comment by paulirish** [comment]
Agree can't be in here for everyone by default.

But it's def how i start greenfield projects. :)

**Comment by jonathantneal** [comment]
A bit of a recap. Based on @paulirish’ excellent input as well as this thread and many other conversations, the following defaults seem safe for both document and app environments.

``` css
* {
    background-repeat: var(--background-repeat, no-repeat);
    flex-flow: var(--flex-flow, column);
    flex-shrink: var(--flex-shrink, 0);
    margin: 0;
    padding: 0;
    position: relative;
}
```

[`position: relative` and `background-repeat: no-repeat`](https://css-tricks.com/things-it-might-be-funuseful-to-try-the-universal-selector-on/) were also advocated by @chriscoyier. The alternate `flex-flow` and `flex-shrink` default seem to have also received widespread adoption.

For the immediate future, I’m going to omit `overflow: hidden` and `display: flex`. Changing the overflow creates too many issues with inline content, as noted in previous comments. Flex would just need more testing, and hopefully by then I can stop worrying about IE8&9. I think it could be a good use case for `inherit`, too.

``` css
* {
    display: inherit;
}

html {
    display: flex;
}

p * {
    display: inline;
}

[hidden], head, body script, body style, body template {
    display: none;
}
```

**Comment by stereokai** [comment]
```
[hidden], head, body script, body style, body template {
    display: none;
}
```

@jonathantneal What's the point with `head, body script`? Isn't it already implicitly like that?

**Comment by jonathantneal** [comment]
@stereokai, with `* { display: inherit }` all that would need to be `display: none` would be `script`, and `style`, you are right.

**Comment by stereokai** [comment]
@jonathantneal Cool. I'm done yet though :D

What's the point of `* { display: inherit }`, and what is the benefit of it in light of issues similar to what's described [here](http://stackoverflow.com/questions/28529865/)?

Thanks

**Comment by jonathantneal** [comment]
I’ll be adding these `flex-flow`, `flex-shrink`, and `position` defaults in the next release.

**Comment by thierryk** [comment]
This:

``` css
* { 
  position:relative;
  overflow:hidden; 
}
```

will create a lot of problems that most authors will be unable to solve for the simple reason that it brings into the picture 2 concepts people have a hard time understanding:
- **containing block**
- **block-formatting context**

Making every single box a _containing block_ will most likely force people to unset this style on parents each time they use `position:absolute` on a box. And we know we can’t really target parents.

Making every single box a _[block-formatting context](http://cssmojo.com/block-formatting-contexts/index.html)_ will prevent the content of boxes to flow around floats, it will prevent margin collapsing, and will also contain floats (you want it or not). 

Making every single box both a containing-block **and** a block-formatting context will **clip** any absolutely positioned nested box. 

So, for these reasons, I don’t think it’d be a good idea to include that rule.

**Comment by jonathantneal** [comment]
A year later, I’m very comfortable with what we’ve got in v4.

**Comment by tomasz1986** [comment]
```
* { 
  position:relative;
  overflow:hidden; 
}
```

causes massive performance issues in Opera 12, i.e. scrolling is extremely jaggy even with no other styles applied to the page.

```
* { 
  position:relative;
  overflow:hidden;
  z-index: 1;
}
```

fixes the lag caused by `position: relative` but even the `overflow: hidden` alone causes some lag too.

Just my random observation.

**Edit**: Settings table cells to `position: relative` also causes bugs in Firefox.
