### ISSUE TITLE
Why do we need `text-indent: 0` for the `table`s?

### ISSUE THREAD

**Issue by yuheiy** [csstools/sanitize.css#214]
https://github.com/csstools/sanitize.css/blob/9bbf845ad6c5f5e5471ed078c73029c2e0bce1c7/sanitize.css#L199

Currently, the default value of `text-indent` seems to be `0` in Chrome, Edge, and Safari, but is this declaration still necessary?

**Comment by abhishekrawat22** [comment]
If you will see in the browser its default value is ```initial``` which itself refers to the default value. But default value can be changed in the parent. So declaring ```text-indent: 0``` will keep us on safe side.

**Comment by jonathantneal** [comment]
@yuheiy, yes to what @abhishekrawat22 has written. 👍

It might be good to update this comment from "_Remove_" to "_Prevent_". It is a browser normalization (_which basically means "bug fix" in this project_) because `table { text-indent: 0 }` ships in Firefox, and it shipped in Internet Explorer. However, now that Firefox is the minority, we should either file bugs with WebKit and Chrome; or do the opposite, normalize Firefox in this project and file a bug with Mozilla.

https://searchfox.org/mozilla-central/source/layout/style/res/html.css#269 (_see also <code><a href="resource://gre-resources/html.css">resource://gre-resources/html.css</a></code> in Firefox itself_)

**Comment by yuheiy** [comment]
@abhishekrawat22 @jonathantneal Thank you for the explanation.

This is just my opinion, but it seems more natural to normalize Firefox. This is because that property is inherited by default.

**Comment by yuheiy** [comment]
Here's what I found out after investigating again:

- Chrome: the `initial` value is set, so it is not inherited. https://chromium.googlesource.com/chromium/src/+/refs/heads/main/third_party/blink/renderer/core/html/resources/html.css#278
- Firefox: the `0` value is set, so it is not inherited. https://searchfox.org/mozilla-central/source/layout/style/res/html.css#269
- Safari: `text-indent` is not declared, so it is inherited. https://trac.webkit.org/browser/trunk/Source/WebCore/css/html.css#L220

It seems that inherited is in the minority.

**Comment by jonathantneal** [comment]
Well, that’s fun. Very well, `0` it stays, after all.
