### ISSUE TITLE
Keep in line with current accessibility standards

### ISSUE THREAD

**Issue by murrayac** [csstools/sanitize.css#50]
Using Genesis Framework who have put extensive work into accessibility in their latest version like underlining links. Thought this would be a good place to start http://genesis-accessible.org/

If this isn't the scope of sanitize.css please delete issue.

**Comment by jonathantneal** [comment]
First, a warning; this site may have hijacked links to shareasale. Links to Genesis Framework seem to be compromised.

Second, thanks for sharing! Words like “accessibility”, “standards” and “framework” get me amped!

In this particularly case, the Leiden theme from Genesis Accessible is too specific for WordPress. What I mean is, it targets WordPress classnames rather than elements, attributes, and agnostic markup patterns.

The generic things it does target trouble me. For instance, the link to explain `body > div { font-size: 1.6rem; }` is not working, but that seems particularly dangerous when it’s labeled as a Chrome fix. I don’t think Chrome has an issue with a `div` being the child of `body`. Similarly, outside WordPress `a img { margin-bottom: -4px; margin-bottom: -0.4rem; }` might trip up developers.

I hope this explains my decision and doesn’t come across as a dismissal of your point. I’m a big fan of accessibility frameworks, so I never, ever want to discourage you or anyone from bringing one to my attention. Please, let me know if there were any particular patterns you found in Genesis Accessible, the plugin, the Leiden theme, or anywhere for that matter that I could pay closer attention to.

**Comment by ghost** [comment]
cc @RRWD

**Comment by rianrietveld** [comment]
@corvannoorloos @jonathantneal 
The functionality the plugin Genesis Accessible and the theme Leiden are now integrated into Genesis core and the Genesis Sample Theme (https://github.com/copyblogger/genesis-sample).
The css is very specific to WordPress and to Genesis.
Is there anything specific you want me to look at here?

**Comment by ghost** [comment]
@RRWD not for me personally. Although I am a big fan of both Leiden and sanitize.css.

<blockquote>First, a warning; this site may have hijacked links to shareasale. Links to Genesis Framework seem to be compromised.</blockquote>

Perhaps I misunderstood, but mainly this and the reasoning after is why I linked both projects. I hope no one minded.

**Comment by jonathantneal** [comment]
First, thanks everyone for chiming in.

Re: hijacked links. I see one for example for “basic Genesis Framework” at http://genesis-accessible.org/installation/

Re: Sanitize / Genesis - anything for us to look at. I think @murrayac wanted me to look for elements to borrow from Genesis / Leiden. While I didn’t find anything, I will say that Sanitize.css could be a great use case for Genesis, paying close attention to https://github.com/10up/sanitize.css/blob/master/sanitize.scss#L270-L298

Even if you did not want to adopt Sanitize.css, this project is dedicated to the public domain, meaning I encourage you to freely take or expand upon anything you like without troubling yourself with licensing. Whatever benefits the users.

**Comment by rianrietveld** [comment]
Well, actually, the links are not hijacked, they're affiliate links, I earn some money with that.
I looked at the scss, specifically targeting ARIA seems like a good idea, yes.
