### ISSUE TITLE
Nested selectors in .css?

### ISSUE THREAD

**Issue by corysimmons** [csstools/sanitize.css#68]
https://github.com/10up/sanitize.css/blob/master/sanitize.css#L29

These are invalid right? I'm not crazy right?

**Comment by corysimmons** [comment]
Nevermind, making my own reset...

**Comment by jonathantneal** [comment]
First, you may have been ultimately looking for [this file](https://github.com/10up/sanitize.css/blob/master/dist/sanitize.css). Second, the great thing about open source is that you can take everything you like about Normalize.css and Sanitize.css and put it into your own reset.

The root sanitize.css file does use [CSS variables](https://drafts.csswg.org/css-variables/) and [nested selectors](https://tabatkins.github.io/specs/css-nesting/), both of which were forthcoming features when I added them (CSS variables have since shown up in some browsers), which is why I distribute the compiled versions. You’ll also find Sass, SCSS, Less, and Stylus versions of Sanitize.css, none of which work without being compiled. The purpose of these is to let you choose your own pre-processor platform.

[Again](https://github.com/necolas/normalize.css/issues/513), I appreciate that you looked over the code.

**Comment by corysimmons** [comment]
@jonathantneal Ah, my bad. Missed the `dist` folder. It is a bit confusing though. What about putting the .css version in a `src` folder or something and putting the compiled version in root?

> Again, I appreciate that you looked over the code.

lol, alright alright

**Comment by jonathantneal** [comment]
About the `src` directory, that’s a great suggestion that I’ve been interested in doing. That would work really well for Normalize.css as well, which folks have [suggested](https://github.com/necolas/normalize.css/issues/222) breaking into parts or leverage a bit of pre-processing. Thanks for bringing it up.

Also, I do mean it when I appreciate that you look over the code. Honestly, I used to look over reset.css and whine about `div` getting reset. Finally, I started writing my own file, and I met Necolas who had been up to the very same thing. Next thing you know, Normalize.css! If my code becomes old and crusty, please write the future. :) And thank you in advance.
