### ISSUE TITLE
Sourcemaps and possible features

### ISSUE THREAD

**Issue by corysimmons** [csstools/sanitize.css#71]
Kudos on the dist folder @jonathantneal 

Should sources be going up a directory? It's current implementation would insinuate the .map was nested in a `css/maps/` folder or something. Is this standard practice? I would expect to drop all these into the same folder and maps just work™

![image](https://cloud.githubusercontent.com/assets/224636/13134124/e0f8e35a-d5d0-11e5-8ddf-dfd87a3dbc1c.png)

In lieu of changing `"sources":["../sanitize.css"]` to `"sources":["sanitize.css"]` maybe put the maps into a `css/maps` folder so they work automatically?

What are your thoughts on integrating any of these features?
- https://github.com/corysimmons/reeeset#features

Happy to start working on this project instead of duplicating our efforts (I think you guys are way ahead of me too so far as all your weird tweaks go). :+1:

**Comment by jonathantneal** [comment]
On sourcemaps: I’m thinking of removing sourcemaps from the compiled version, and putting that compiled version in the root of this project. See https://github.com/10up/sanitize.css/tree/feature/reorganization. The idea is that sourcemaps would be compiled by people actually using the lib versions with sourcemaps on. What do you think?

On integrating reeeset features: I’ll checkout the diff between ours and see if those features could be ported. If they don’t immediately seem pullable, I’d at least explain the rationale and be open to discussing it so that I could learn how it’s serving your usecase.

**Comment by corysimmons** [comment]
tbh I don't think preprocessors need sourcemaps at all. They can, and probably should, generate sourcemaps with their preprocessor flavor (I don't think they'd be 1:1 if sass outputted it's weird default output and stylus outputted compressed?). So I think it makes sense to keep the map with the vanilla css.

I imagine structure like:

```
- dist
  - css
    - sanitize.css
    - sanitize.css.map
    - sanitize.min.css
    - sanitize.min.css.map
  - less
    - sanitize.less
  - scss
    - sanitize.scss
  - sass
    - sanitize.sass
  - stylus
    - sanitize.styl
- src
  ...
```

With a similar structure for src.

Looks a little bulky, but dist can/should be cleaned, built, and tested by a task, so really you'd just need to fool around in `src`.

I suppose you could get rid of the folders in `src` if you really wanted to, but I don't think they'd hurt. Maybe add a README to each of them with instructions for how to use sanitize with that particular preprocessor?

tbh I'm not worried about reeeset's features get ported. I'm not sure any of them are doing much different from what you're doing, and the ones that obviously are, might not be a good fit for this project. Either way, take a quick peek at them and lemme know if you have any questions.

I'm also in talks with https://github.com/ZDroid/sanitize.css/issues/6#issuecomment-185551429 to see if he'll relinquish his CDNjs name so you guys can get it.

Also talking to CodePen about getting sanitize.css added as an alternative to normalize and meyer's reset. If that happens, sanitize will probably get a bit more attention. :+1:

**Comment by jonathantneal** [comment]
Thanks again. I’m think source maps should be generated during build, where sanitize.css (precompiled or otherwise) can be properly mapped however it is implement. I’m closing this out, but let me know what you think of the new project structure. Also, thanks about looking into getting sanitize.css on cdns over. I remember when that project was being built, I voiced similar concerns (since this project also outdates that one).

**Comment by corysimmons** [comment]
Sure np.

**Comment by dbox** [comment]
https://twitter.com/MarcusTister/status/705034961003347968

Chris Coyer liked this tweet, so it'd seem like there is some momentum to getting it added codepen.

**Comment by corysimmons** [comment]
Yeah they seemed interested in it when I emailed. I'm not sure why some things take a long time. This feature seems like it'd take 10 minutes to review and add.

Excited about never using Normalize again.
